### PR TITLE
Updated the code as a Jupyter notbook 

### LINKED ISSUE #1: Reformat this code as a Jupyter Notebook
It would be much better for visualization of the FT properties (phase/magnitude, shifting, aliasing., spiking...) to present these simulations in a Jupyter Notebook.

### PR DESCRIPTION
**Pull request by gaspardcereza**
The Notebook briefly presents the principles of the Fourier transform and its main properties in 1D and 2D. It then shows different Fourier related artifacts usually encountered in MR applications and tries to replicate them.

I tested the notebook on binder and it works just fine. 

Every feedback would be greatly appreciated (about the code, the figures, the animations, the explanations, missing artifacts, typos or whatever you think might be better) !

Closes #1

### CODE REVIEW

**Comment by po09i** [comment]
Could not install the environment locally. I opened #3

**Review by po09i — COMMENTED** [review]
Quick comments:
- I don't know if this repo has size constraints but but the notebook is already 33mb without the functions loaded (probably due to the image being loaded)
- _Fourier series: everything is sinusoidal!_
  - Is it possible to show the initial plots without the maximum number of sinusoids as default? I found the second plot overwhelming when I looked at it for the first time.
  - Some sinusoids have sharp edges, is it a sampling issue? It should be fixed or mentioned I think.
- _The Fourier Domain: just another way of seeing things_
  - Typo in _Fourier transform_: "This two representations" (These)
  - Typo in _Discrete Fourier Transform_: "use the example a a signal" (double a)
  - Typo in _Phase spectrum_:  "It this thus very important"
- _Aliasing and Nyquist-Shannon theorem_
  - Typo in first paragraph: "signal are at larger than the sampling frequency"
  - Typo in 5th paragraph:  "2 samples by period" (per)
  - Typo in _High/low frequency components_: "Fourier Transform is an interseting tool in"
  - Typo in _High/low frequency components_: "Compare to a spatial filtering" (Compared)
- _Orientation of the frequencies in the image_
  - Typo in 2nd paragraph:  "image is encoding in the angle" (encoded)
  - Specify where the mask is in the title or description (Not obvious where the mask is related to the center of the image)
- _Fourier related MRI artifacts_
  - "the signal measured during an MRI scan corresponds to the k-space of the final image." Mention again that k-space = Fourier space
  - Typo in last paragraph: "show of this property"
  - _Herringbone artifact_
    - Typo in 2nd paragraph: "due to an punctual electrical " (a)
    - Show shifted FFT instead of non-shifted
  - _Wrap-around Artifact_
    - Typo in 3rd paragraph: "sampling-frequency is to low compared" (too)
  - _Gibbs artifact (ringing)_
    - Typo in 3rd paragraph: "signal with not enough sinusoids" (without)
    - Zoom more on a region
    - Typo in what can be done...: ) "before preocessing"
- It finishes rather abruptly

Really nice work! This is a really nice overview of Fourier and the artifacts related to MRIs.

**Comment by gaspardcereza** [comment]
> Quick comments:
> 
> * I don't know if this repo has size constraints but but the notebook is already 33mb without the functions loaded (probably due to the image being loaded)
> * _Fourier series: everything is sinusoidal!_
>   
>   * Is it possible to show the initial plots without the maximum number of sinusoids as default? I found the second plot overwhelming when I looked at it for the first time.
>   * Some sinusoids have sharp edges, is it a sampling issue? It should be fixed or mentioned I think.

> * _Orientation of the frequencies in the image_
>   
>   * Typo in 2nd paragraph:  "image is encoding in the angle" (encoded)
>   * Specify where the mask is in the title or description (Not obvious where the mask is related to the center of the image)
> * _Fourier related MRI artifacts_
>   
>   * "the signal measured during an MRI scan corresponds to the k-space of the final image." Mention again that k-space = Fourier space
>   * Typo in last paragraph: "show of this property"
>   * _Herringbone artifact_
>     
>     * Typo in 2nd paragraph: "due to an punctual electrical " (a)
>     * Show shifted FFT instead of non-shifted
>   * _Wrap-around Artifact_
>     
>     * Typo in 3rd paragraph: "sampling-frequency is to low compared" (too)
>   * _Gibbs artifact (ringing)_
>     
>     * Typo in 3rd paragraph: "signal with not enough sinusoids" (without)
>     * Zoom more on a region
>     * Typo in what can be done...: ) "before preocessing"
> * It finishes rather abruptly
> 
> Really nice work! This is a really nice overview of Fourier and the artifacts related to MRIs.

**Comment by gaspardcereza** [comment]
Thanks for the awesome feedback @po09i  (and for spotting so many typos 😉 )!

I think I managed to address most of your comments, and here are some additional info:

> * I don't know if this repo has size constraints but but the notebook is already 33mb without the functions loaded (probably due to the image being loaded)

It is indeed heavy but I don't see any alternative to having these images (right now they are embedded in the notebook but they would be the same size if they were in an external folder...).

> * _Fourier series: everything is sinusoidal!_
>   
>   * Is it possible to show the initial plots without the maximum number of sinusoids as default? I found the second plot overwhelming when I looked at it for the first time.

I found a way to do so but I had to move from the original callbacks I was using for the widgets. Consequence: Only one widget can be interactive at a time --> I added comments specifying that if a widget is not responding, the code cell must be run again. On the bright side, It forced me to move away from javascript callbacks so everything is 100% python now (but it is also slower...). 

>   * Some sinusoids have sharp edges, is it a sampling issue? It should be fixed or mentioned I think.

I cannot really change that as it is a consequence of shannon-nyquist (high frequency components are not sampled fast enough to be perfectly sinusoidal) --> I added a comment explaining this

> * _Orientation of the frequencies in the image_
>   
>   * Specify where the mask is in the title or description (Not obvious where the mask is related to the center of the image)

I  change the masks so that they're closer to the edges (this way we easily understand where they are related to the center)

> * It finishes rather abruptly

If you have any idea how what could be a interesting way to conclude just let me know !

**Comment by jcohenadad** [comment]
> right now they are embedded in the notebook but they would be the same size if they were in an external folder

could you remove them from the notebook, add them to the repos and link them inside the notebook so that every time the notebook is updated the repos doesn't accumulate 35MB of fat each time-- thx-- it will also make the notebook lighter (for moving it around, download, etc.)

**Comment by gaspardcereza** [comment]
> could you remove them from the notebook, add them to the repos and link them inside the notebook so that every time the notebook is updated the repos doesn't accumulate 35MB of fat each time-- thx-- it will also make the notebook lighter (for moving it around, download, etc.)

Done ! (Hope I did not forget any image)

**Comment by po09i** [comment]
> I found a way to do so but I had to move from the original callbacks I was using for the widgets. Consequence: Only one widget can be interactive at a time --> I added comments specifying that if a widget is not responding, the code cell must be run again. On the bright side, It forced me to move away from javascript callbacks so everything is 100% python now (but it is also slower...).

I tested locally and the changes make it feel rather choppy/slow.. If I had to chose between both versions I prefer the original one.. Unless you find another solution...

**Comment by po09i** [comment]
I can't see the figures locally and I'm getting this warning message
Screen Shot 2021-06-10 at 12 05 16

**Comment by gaspardcereza** [comment]
> I tested locally and the changes make it feel rather choppy/slow.. If I had to chose between both versions I prefer the original one.. Unless you find another solution...

I'll see if I can find a good compromise

**Comment by gaspardcereza** [comment]
> I can't see the figures locally and I'm getting this warning message

It seems that there's a problem with the Matplotlib settings but I don't understand why they don't happen on my end. Is `env-fourier` the environment you are running the notebook in ?

**Comment by jcohenadad** [comment]
> > I tested locally and the changes make it feel rather choppy/slow.. If I had to chose between both versions I prefer the original one.. Unless you find another solution...
> 
> I'll see if I can find a good compromise

is this caused by the figures being removed out of the notebook? if so, we can consider put them back (more pros than cons)

**Comment by gaspardcereza** [comment]
> is this caused by the figures being removed out of the notebook? if so, we can consider put them back (more pros than cons)

No we are talking about the animations. Originally they were coded in javascript and were much faster but the only way I found to reduce the number of sinusoids in the initial plot was to use a different type of callbacks. They both have pros and cons that I can list here:

- Javascript solution (original):
  -  Pros:
     - Fast (no delay between action/reaction)
     - All widgets are working simultaneously
  - Cons:
    - I couldn't set any number of sinusoids in the initial plot (But I might try again maybe there's a way to do so)
    - No debugging allowed for the Javascript part

- Python solution: 
  - Pros: 
    - Cleaner to have only one language
    - Easier to debug
    - Easy to set the initial number of displayed sinusoids
  - Cons: 
    - Only one widget working at a time (need to rerun the corresponding cell before using a widget) 
    - Delays between the user's action and the figures' updates

**Review by jcohenadad — APPROVED** [review]
@gaspardcereza I just went through the entire notebook and it it AMAZING!! Very clear and comprehensive. And the interactive figures are working very well on my end (so I vote for the "Bokeh python" solution). Thank you so much for putting this together. This is an incredibly useful pedagogical tool. You can be proud of yourself.

**Comment by KevinBerard** [comment]
I went throught the entire notebook after installing it on Windows without issue. As @jcohenadad said, it is amazing and I would had love to have this when starting in image processing in GBM8770 and then GBM8378. These are two suggestions that I have after my lecture :

- The Fourier Domain: just another way of seeing things
  - `It has a magnitude component and a phase component, it is thus a complex domain.` Suggestion : Maybe you could explain why?
  - The k-space explaination promised never really did happen later in the document
- Wrap-around Artifact
  - `On modern scanners, this usually only occurs in the phase direction (phase wrap-around)` Is there an explanation or figure to show the difference (or the lack of) between frequency wrap-around and phase wrap-around?

**Review by KevinBerard — APPROVED** [review]

**Comment by po09i** [comment]
> > I can't see the figures locally and I'm getting this warning message
> 
> It seems that there's a problem with the Matplotlib settings but I don't understand why they don't happen on my end. Is `env-fourier` the environment you are running the notebook in ?

Yes I was in the `env-fourier` environment. The animations were working (they were slow but working)

**Comment by gaspardcereza** [comment]
> * Javascript solution (original):
>   
>   * Pros:
>     
>     * Fast (no delay between action/reaction)
>     * All widgets are working simultaneously
>   * Cons:
>     
>     * I couldn't set any number of sinusoids in the initial plot (But I might try again maybe there's a way to do so)
>     * No debugging allowed for the Javascript part
> * Python solution:
>   
>   * Pros:
>     
>     * Cleaner to have only one language
>     * Easier to debug
>     * Easy to set the initial number of displayed sinusoids
>   * Cons:
>     
>     * Only one widget working at a time (need to rerun the corresponding cell before using a widget)
>     * Delays between the user's action and the figures' updates

In the end, I decided to go with a Javascript solution because the python one was slow on my end too. I struggled a lot but found a way to display a low initial number of sinusoids, making the number of pros for the JS solution much higher than for the python one.

**Comment by gaspardcereza** [comment]
> I went throught the entire notebook after installing it on Windows without issue. As @jcohenadad said, it is amazing and I would had love to have this when starting in image processing in GBM8770 and then GBM8378. These are two suggestions that I have after my lecture :
> 
> * The Fourier Domain: just another way of seeing things
>   
>   * `It has a magnitude component and a phase component, it is thus a complex domain.` Suggestion : Maybe you could explain why?
>   * The k-space explaination promised never really did happen later in the document
> * Wrap-around Artifact
>   
>   * `On modern scanners, this usually only occurs in the phase direction (phase wrap-around)` Is there an explanation or figure to show the difference (or the lack of) between frequency wrap-around and phase wrap-around?

Thanks so much @KevinBerard for the comments I'll try to address them ASAP !

**Comment by gaspardcereza** [comment]
@jcohenadad @po09i, while addressing  @KevinBerard's comments, I realized the encoding part was not very detailed so I added a lot of figures/equations in a new section `Why is the Fourier theory so important for MRI ?` to explain how it works. Feedback more than welcome as always !

**Comment by KevinBerard** [comment]
Great addition! I really like it. Here is a comment on the new section :

- Why is the Fourier theory so important for MRI ?
  - K-space
    - `𝜔0=𝛾𝐵0` the 𝛾 is never explained or mentionned outside of the equations

**Comment by evaalonsoortiz** [comment]
I am currently making my way through the notebook (great work! - very helpful resource for students). I will add comments as they arise. The first thing I've come across is the following:

The following text in the k-space section "By finding a way to convert  𝑒−𝑖𝜔 <sub>0</sub>𝑡  into  𝑒−𝑖2𝜋𝑢𝑥𝑒−𝑖2𝜋𝑣𝑦  the image  ℎ(𝑥,𝑦) ... "

In MRI we create the  𝑒−𝑖2𝜋𝑢𝑥𝑒−𝑖2𝜋𝑣𝑦 terms by turning on the spatial encoding gradients, but these do not "transform" the 𝑒−𝑖𝜔 <sub>0</sub>𝑡 term, as the sentence implies. That term remains there and is dropped because during post processing, the signal is demodulated.

I was not able to run the code cells. It doesn't seem that the requirements are being called... I loaded everything in binder and opened the Fourier file, as per the instructions. Am I missing something?

**Comment by evaalonsoortiz** [comment]
Under the "Phase encoding" section, in the first equation there is a closing bracket but no opening bracket in the exponent.

**Comment by evaalonsoortiz** [comment]
clipping artifact section typo: "as the high values are usually the one corresponding" should be "as the high values are usually the ones corresponding"

**Comment by evaalonsoortiz** [comment]
I have no more comments to add - once again, fantastic job!!

**Comment by gaspardcereza** [comment]
> I was not able to run the code cells. It doesn't seem that the requirements are being called... I loaded everything in binder and opened the Fourier file, as per the instructions. Am I missing something?

That is weird it works well on my end (I clicked on the badge in the README to launch Binder). Did it return any error @evaalonsoortiz ?

**Pull request merged**
